#!/bin/bash -eux

MYSQL_ROOT_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`

echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" > .env
echo "WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env
echo "MAIL_PASS=${MAIL_PASS}" >> .env
echo "MAIL_USER=${MAIL_USER}" >> .env
echo "MAIL_HOST=${MAIL_HOST}" >> .env
echo "MAIL_PORT=${MAIL_PORT}" >> .env
echo "MAIL_SECURITY=tls" >> .env
echo "SUBNET=${SUBNET}" >> .env
echo "WORDPRESS_VERSION=4.9.8-fpm" >> .env
echo "MYSQL_VERSION=5.7" >> .env
